// ============================================================
// INVESTIGATOR TOOLS DATA MODEL & STORE
// Private Intelligence & Investigations Platform
// ============================================================

export type ToolCategory =
  | "IDENTITY & PEOPLE"
  | "IMAGE & FACE"
  | "SOCIAL / SOCMINT"
  | "USERNAME & EMAIL"
  | "WEB & ARCHIVES"
  | "GEOSPATIAL / GEOINT"
  | "CAMERAS & LIVE SOURCES"
  | "COMPANIES & CORPORATE"
  | "PROPERTY / LAND"
  | "DOMAINS & INFRASTRUCTURE"
  | "DOCUMENTS & FILE ANALYSIS"
  | "LINK ANALYSIS"
  | "VEHICLES / TRANSPORT"
  | "PUBLIC RECORDS"
  | "SEARCH & DISCOVERY"
  | "EVIDENCE PRESERVATION"
  | "INVESTIGATOR UTILITIES";

export type ToolStatus = "Active" | "Review" | "Unavailable" | "Retired";
export type ToolAccessType = "Free / Open" | "Freemium" | "Subscription" | "Paid / Credit" | "Restricted";
export type ToolRiskLevel = "Low" | "Medium" | "High";

export interface ToolEntity {
  tool_id: string;
  name: string;
  slug: string;
  description: string;
  category: ToolCategory;
  primary_use: string;
  url: string;
  documentation_url?: string;
  icon?: string;
  status: ToolStatus;
  access_type: ToolAccessType;
  requires_account: boolean;
  requires_subscription: boolean;
  risk_level: ToolRiskLevel;
  notes?: string;
  sort_order: number;
  is_featured: boolean;
  created_at: string;
  updated_at: string;
  // Governance & compliance fields
  terms_reviewed_at?: string;
  privacy_reviewed_at?: string;
  last_checked_at?: string;
  approved_by?: string;
  internal_risk_classification?: string;
}

export const TOOL_CATEGORIES: ToolCategory[] = [
  "IDENTITY & PEOPLE",
  "IMAGE & FACE",
  "SOCIAL / SOCMINT",
  "USERNAME & EMAIL",
  "WEB & ARCHIVES",
  "GEOSPATIAL / GEOINT",
  "CAMERAS & LIVE SOURCES",
  "COMPANIES & CORPORATE",
  "PROPERTY / LAND",
  "DOMAINS & INFRASTRUCTURE",
  "DOCUMENTS & FILE ANALYSIS",
  "LINK ANALYSIS",
  "VEHICLES / TRANSPORT",
  "PUBLIC RECORDS",
  "SEARCH & DISCOVERY",
  "EVIDENCE PRESERVATION",
  "INVESTIGATOR UTILITIES",
];

export const INITIAL_TOOLS: ToolEntity[] = [
  // IMAGE & FACE
  {
    tool_id: "tool-001",
    name: "FaceCheck.ID",
    slug: "facecheck-id",
    description: "Reverse facial-image search across publicly indexed web content and social networks.",
    category: "IMAGE & FACE",
    primary_use: "Possible online appearances of a face and facial cross-referencing.",
    url: "https://facecheck.id",
    documentation_url: "https://facecheck.id/about",
    status: "Active",
    access_type: "Freemium",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Medium",
    notes: "Useful for initial facial discovery. Never treat similarity score or algorithmic match as confirmed identification. Corroborate independently.",
    sort_order: 1,
    is_featured: true,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-09-10",
    privacy_reviewed_at: "2025-09-10",
    last_checked_at: "2025-10-05",
    approved_by: "David Mercer",
    internal_risk_classification: "GDPR LIA Required / Investigative Lead Only",
  },
  {
    tool_id: "tool-002",
    name: "Google Lens",
    slug: "google-lens",
    description: "General visual search, product matching, location recognition, and reverse image lookups.",
    category: "IMAGE & FACE",
    primary_use: "Identifying objects, logos, landmarks, clothing, and duplicate photographs.",
    url: "https://lens.google.com",
    documentation_url: "https://support.google.com/websearch/answer/1325808",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Ideal for verifying location backgrounds, commercial signage, and duplicate online photography.",
    sort_order: 2,
    is_featured: true,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-08-15",
    privacy_reviewed_at: "2025-08-15",
    last_checked_at: "2025-10-04",
    approved_by: "Sarah Chen",
    internal_risk_classification: "Standard OSINT",
  },
  {
    tool_id: "tool-003",
    name: "TinEye",
    slug: "tineye",
    description: "Dedicated reverse image search engine tracking image history, modifications, and earlier appearances.",
    category: "IMAGE & FACE",
    primary_use: "Establishing the earliest known date an image was uploaded and discovering original resolutions.",
    url: "https://tineye.com",
    documentation_url: "https://tineye.com/faq",
    status: "Active",
    access_type: "Freemium",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Best for timestamping earliest image crawl dates and detecting cropped or modified versions.",
    sort_order: 3,
    is_featured: false,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-07-20",
    privacy_reviewed_at: "2025-07-20",
    last_checked_at: "2025-10-02",
    approved_by: "Sarah Chen",
    internal_risk_classification: "Standard OSINT",
  },

  // IDENTITY / SOCMINT / USERNAME / EMAIL
  {
    tool_id: "tool-004",
    name: "OSINT Industries",
    slug: "osint-industries",
    description: "Real-time identity discovery and digital footprint enrichment across 300+ modules using emails or phone numbers.",
    category: "SOCIAL / SOCMINT",
    primary_use: "Discovering connected social profiles, profile pictures, and active registrations from email/phone.",
    url: "https://osint.industries",
    documentation_url: "https://docs.osint.industries",
    status: "Active",
    access_type: "Subscription",
    requires_account: true,
    requires_subscription: true,
    risk_level: "Medium",
    notes: "High-accuracy live lookups. Verify operational legitimacy and retain search log for case audit.",
    sort_order: 4,
    is_featured: true,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-09-01",
    privacy_reviewed_at: "2025-09-01",
    last_checked_at: "2025-10-05",
    approved_by: "David Mercer",
    internal_risk_classification: "Authorised Account Only / Audit Logging Required",
  },
  {
    tool_id: "tool-005",
    name: "Sherlock",
    slug: "sherlock",
    description: "Open-source CLI/web tool for hunting down social media accounts by username across hundreds of networks.",
    category: "USERNAME & EMAIL",
    primary_use: "Username enumeration to locate profile handles across social platforms.",
    url: "https://sherlock-project.github.io",
    documentation_url: "https://github.com/sherlock-project/sherlock#readme",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Matches on handle presence only. Corroborate that the profile owner matches the subject of inquiry.",
    sort_order: 5,
    is_featured: true,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-06-10",
    privacy_reviewed_at: "2025-06-10",
    last_checked_at: "2025-09-28",
    approved_by: "Sarah Chen",
    internal_risk_classification: "Standard OSINT",
  },
  {
    tool_id: "tool-006",
    name: "Maigret",
    slug: "maigret",
    description: "Advanced username discovery tool parsing profiles, extracting dossier data and generating recursive links.",
    category: "USERNAME & EMAIL",
    primary_use: "Deep profile extraction, bio aggregation, and link discovery based on usernames.",
    url: "https://github.com/soxoj/maigret",
    documentation_url: "https://maigret.readthedocs.io",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Generates recursive reports. Review scraped fields for false positives before noting in case files.",
    sort_order: 6,
    is_featured: false,
    created_at: "2025-02-01T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-06-10",
    privacy_reviewed_at: "2025-06-10",
    last_checked_at: "2025-09-28",
    approved_by: "Sarah Chen",
    internal_risk_classification: "Standard OSINT",
  },
  {
    tool_id: "tool-007",
    name: "Epieos",
    slug: "epieos",
    description: "Reverse email and phone number OSINT search engine querying services without notifying targets.",
    category: "USERNAME & EMAIL",
    primary_use: "Google account review (reviews, maps activity, calendar, profile picture) and service registration checks.",
    url: "https://epieos.com",
    documentation_url: "https://epieos.com/faq",
    status: "Active",
    access_type: "Freemium",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Non-intrusive metadata inspection. Results must be independently confirmed with matter timestamps.",
    sort_order: 7,
    is_featured: true,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-08-20",
    privacy_reviewed_at: "2025-08-20",
    last_checked_at: "2025-10-03",
    approved_by: "Sarah Chen",
    internal_risk_classification: "Standard OSINT",
  },
  {
    tool_id: "tool-008",
    name: "Have I Been Pwned",
    slug: "have-i-been-pwned",
    description: "Comprehensive database of historical data breaches containing compromised email addresses and paste dumps.",
    category: "IDENTITY & PEOPLE",
    primary_use: "Identifying which historical breaches, platforms, and years an email address was registered on.",
    url: "https://haveibeenpwned.com",
    documentation_url: "https://haveibeenpwned.com/FAQs",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Confirms presence of an account on services as of the breach date. Never download or traffic in plaintext passwords.",
    sort_order: 8,
    is_featured: true,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-08-01",
    privacy_reviewed_at: "2025-08-01",
    last_checked_at: "2025-10-01",
    approved_by: "David Mercer",
    internal_risk_classification: "Authorised Research",
  },

  // WEB & ARCHIVES / SEARCH
  {
    tool_id: "tool-009",
    name: "Wayback Machine",
    slug: "wayback-machine",
    description: "Digital archive of the World Wide Web containing hundreds of billions of historical page captures.",
    category: "WEB & ARCHIVES",
    primary_use: "Viewing deleted websites, historical company staff pages, altered contact details, and past claims.",
    url: "https://archive.org/web/",
    documentation_url: "https://help.archive.org/help/wayback-machine-general-information/",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Crucial for corporate due diligence and fraud investigations. Always capture timestamped SHA-256 evidence records.",
    sort_order: 9,
    is_featured: true,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-07-15",
    privacy_reviewed_at: "2025-07-15",
    last_checked_at: "2025-10-05",
    approved_by: "David Mercer",
    internal_risk_classification: "Standard OSINT",
  },
  {
    tool_id: "tool-010",
    name: "Google Search",
    slug: "google-search",
    description: "Global web search engine with extensive indexing and algorithmic relevancy ranking.",
    category: "SEARCH & DISCOVERY",
    primary_use: "Broad-spectrum entity discovery, press coverage, public mentions, and news reporting.",
    url: "https://www.google.com",
    documentation_url: "https://support.google.com/websearch",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Use clean browser profiles or incognito sessions to prevent personalised tracking from biasing results.",
    sort_order: 10,
    is_featured: false,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-05-10",
    privacy_reviewed_at: "2025-05-10",
    last_checked_at: "2025-10-05",
    approved_by: "Sarah Chen",
    internal_risk_classification: "Standard Search",
  },
  {
    tool_id: "tool-011",
    name: "Bing",
    slug: "bing",
    description: "Alternative search engine with distinct crawler indexing algorithms and image caching.",
    category: "SEARCH & DISCOVERY",
    primary_use: "Secondary search discovery, different backlink indexing, and unindexed alternative results.",
    url: "https://www.bing.com",
    documentation_url: "https://support.microsoft.com/en-us/topic/bing-search-help-745a3311-665b-4c59-bfad-1df35b44ec1c",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Often retains cached entries and thumbnail previews after original removal from Google.",
    sort_order: 11,
    is_featured: false,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-05-10",
    privacy_reviewed_at: "2025-05-10",
    last_checked_at: "2025-10-04",
    approved_by: "Sarah Chen",
    internal_risk_classification: "Standard Search",
  },
  {
    tool_id: "tool-012",
    name: "Google Advanced Search",
    slug: "google-advanced-search",
    description: "Structured interface for executing complex search operators (site:, filetype:, inurl:, exact matches).",
    category: "SEARCH & DISCOVERY",
    primary_use: "Targeted document searching (filetype:pdf), corporate portal discovery, and strict dorking.",
    url: "https://www.google.com/advanced_search",
    documentation_url: "https://support.google.com/websearch/answer/2466433",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Essential for surfacing leaked corporate disclosures, policy documents, and unlisted subdirectories.",
    sort_order: 12,
    is_featured: true,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-05-10",
    privacy_reviewed_at: "2025-05-10",
    last_checked_at: "2025-10-05",
    approved_by: "Sarah Chen",
    internal_risk_classification: "Standard Search",
  },

  // CAMERAS & LIVE SOURCES
  {
    tool_id: "tool-013",
    name: "WorldCam",
    slug: "worldcam",
    description: "Aggregator and directory of public live webcams, traffic cameras, and geographic video feeds.",
    category: "CAMERAS & LIVE SOURCES",
    primary_use: "Verifying live environmental conditions, weather, traffic patterns, and public venue density.",
    url: "https://worldcam.eu",
    documentation_url: "https://worldcam.eu/about",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Only public live stream feeds. Useful for planning surveillance access routes and confirming weather during timeline events.",
    sort_order: 13,
    is_featured: false,
    created_at: "2025-02-10T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-08-01",
    privacy_reviewed_at: "2025-08-01",
    last_checked_at: "2025-10-02",
    approved_by: "Thomas Hardy",
    internal_risk_classification: "Public Feeds Only",
  },
  {
    tool_id: "tool-014",
    name: "NStarLive",
    slug: "nstarlive",
    description: "Maritime, offshore, and infrastructure positioning feed directory.",
    category: "CAMERAS & LIVE SOURCES",
    primary_use: "Monitoring transit corridors and open infrastructure cameras.",
    url: "https://www.nstarlive.com",
    status: "Review",
    access_type: "Restricted",
    requires_account: true,
    requires_subscription: true,
    risk_level: "Medium",
    notes: "Official provider portal pending updated licensing verification. Review access credentials prior to operational deployment.",
    sort_order: 14,
    is_featured: false,
    created_at: "2025-03-01T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-06-15",
    privacy_reviewed_at: "2025-06-15",
    last_checked_at: "2025-09-30",
    approved_by: "David Mercer",
    internal_risk_classification: "Pending Licensing Review",
  },
  {
    tool_id: "tool-015",
    name: "REVEALER.UK",
    slug: "revealer-uk",
    description: "UK specialised open intelligence search aggregator and public records portal.",
    category: "CAMERAS & LIVE SOURCES",
    primary_use: "UK regional directory lookups and cross-jurisdictional open record aggregation.",
    url: "https://revealer.uk",
    status: "Review",
    access_type: "Freemium",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Medium",
    notes: "Requires manual corroboration against primary statutory registers. Useful for lead generation.",
    sort_order: 15,
    is_featured: false,
    created_at: "2025-04-01T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-07-01",
    privacy_reviewed_at: "2025-07-01",
    last_checked_at: "2025-09-25",
    approved_by: "David Mercer",
    internal_risk_classification: "Secondary Aggregate",
  },

  // GEOSPATIAL / GEOINT
  {
    tool_id: "tool-016",
    name: "Google Maps",
    slug: "google-maps",
    description: "Comprehensive global mapping, Street View reconnaissance, satellite photography, and route calculations.",
    category: "GEOSPATIAL / GEOINT",
    primary_use: "Surveillance reconnaissance, vantage point planning, entry/exit analysis, and distance verification.",
    url: "https://maps.google.com",
    documentation_url: "https://support.google.com/maps",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Street View images include capture dates in the corner. Always record capture month/year in reconnaissance reports.",
    sort_order: 16,
    is_featured: true,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-06-01",
    privacy_reviewed_at: "2025-06-01",
    last_checked_at: "2025-10-05",
    approved_by: "Thomas Hardy",
    internal_risk_classification: "Standard Mapping",
  },
  {
    tool_id: "tool-017",
    name: "Google Earth",
    slug: "google-earth",
    description: "3D virtual globe with historical satellite imagery archives, terrain elevation, and measurement tools.",
    category: "GEOSPATIAL / GEOINT",
    primary_use: "Historical timeline satellite imagery to verify changes in structures, vehicles, or property over years.",
    url: "https://earth.google.com/web/",
    documentation_url: "https://support.google.com/earth",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Use Google Earth Pro desktop if specific historical satellite slider captures are required for court bundles.",
    sort_order: 17,
    is_featured: true,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-06-01",
    privacy_reviewed_at: "2025-06-01",
    last_checked_at: "2025-10-05",
    approved_by: "Thomas Hardy",
    internal_risk_classification: "Standard Geospatial",
  },
  {
    tool_id: "tool-018",
    name: "OpenStreetMap",
    slug: "openstreetmap",
    description: "Collaborative, open-data global mapping platform with detailed building footprints and footpaths.",
    category: "GEOSPATIAL / GEOINT",
    primary_use: "Identifying pedestrian cut-throughs, building numbers, rights-of-way, and non-vehicular escape paths.",
    url: "https://www.openstreetmap.org",
    documentation_url: "https://wiki.openstreetmap.org",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Frequently has more precise rural and pedestrian trail detail than commercial maps. Excellent for foot surveillance.",
    sort_order: 18,
    is_featured: false,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-05-15",
    privacy_reviewed_at: "2025-05-15",
    last_checked_at: "2025-10-03",
    approved_by: "Thomas Hardy",
    internal_risk_classification: "Standard Mapping",
  },
  {
    tool_id: "tool-019",
    name: "Mapillary",
    slug: "mapillary",
    description: "Crowdsourced street-level imagery platform captured by dashcams, cyclists, and pedestrians globally.",
    category: "GEOSPATIAL / GEOINT",
    primary_use: "Alternative recent street-level imagery where Google Street View is outdated or unavailable.",
    url: "https://www.mapillary.com",
    documentation_url: "https://help.mapillary.com",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Contains recent crowd captures often weeks old compared to years on commercial alternatives.",
    sort_order: 19,
    is_featured: false,
    created_at: "2025-02-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-07-10",
    privacy_reviewed_at: "2025-07-10",
    last_checked_at: "2025-10-01",
    approved_by: "Thomas Hardy",
    internal_risk_classification: "Standard Streetview",
  },

  // COMPANIES & CORPORATE
  {
    tool_id: "tool-020",
    name: "Companies House",
    slug: "companies-house",
    description: "Official statutory UK registry of registered companies, officers, PSCs, charges, accounts, and liquidations.",
    category: "COMPANIES & CORPORATE",
    primary_use: "Directorship verification, corporate asset tracing, disqualification register, and registered offices.",
    url: "https://find-and-update.company-information.service.gov.uk",
    documentation_url: "https://www.gov.uk/government/organisations/companies-house/about",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Primary statutory authority for UK corporate investigations. Always download original filing PDFs for exhibits.",
    sort_order: 20,
    is_featured: true,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-09-01",
    privacy_reviewed_at: "2025-09-01",
    last_checked_at: "2025-10-06",
    approved_by: "David Mercer",
    internal_risk_classification: "Statutory Authority",
  },
  {
    tool_id: "tool-021",
    name: "OpenCorporates",
    slug: "opencorporates",
    description: "The largest open database of companies in the world, aggregating records across 140+ jurisdictions.",
    category: "COMPANIES & CORPORATE",
    primary_use: "Cross-border entity tracing, offshore parent company discovery, and international corporate networks.",
    url: "https://opencorporates.com",
    documentation_url: "https://opencorporates.com/info/about",
    status: "Active",
    access_type: "Freemium",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Essential for linking UK directors to offshore corporate structures in Delaware, Cyprus, BVI, or Luxembourg.",
    sort_order: 21,
    is_featured: true,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-08-10",
    privacy_reviewed_at: "2025-08-10",
    last_checked_at: "2025-10-04",
    approved_by: "David Mercer",
    internal_risk_classification: "International Registry",
  },

  // DOCUMENTS & FILE ANALYSIS / EVIDENCE
  {
    tool_id: "tool-022",
    name: "ExifTool",
    slug: "exiftool",
    description: "Standard command-line and web metadata reader for reading, writing, and parsing metadata across 100+ file formats.",
    category: "DOCUMENTS & FILE ANALYSIS",
    primary_use: "Extracting camera serials, GPS coordinates, capture timestamps, lens data, and software history from files.",
    url: "https://exiftool.org",
    documentation_url: "https://exiftool.org/faq.html",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Golden standard for digital evidence validation. Run locally on evidence files before submitting to case bundles.",
    sort_order: 22,
    is_featured: true,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-08-01",
    privacy_reviewed_at: "2025-08-01",
    last_checked_at: "2025-10-01",
    approved_by: "Sarah Chen",
    internal_risk_classification: "Local Processing Utility",
  },
  {
    tool_id: "tool-023",
    name: "InVID",
    slug: "invid",
    description: "Verification toolkit plugin for debunking fake video files and photos with keyframe decomposition.",
    category: "DOCUMENTS & FILE ANALYSIS",
    primary_use: "Segmenting video into keyframes, reverse image searching frames, and reading video container metadata.",
    url: "https://www.invid-project.eu/tools-and-services/invid-verification-plugin/",
    documentation_url: "https://www.invid-project.eu",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Critical for verifying that video evidence supplied by clients or third parties is authentic and original.",
    sort_order: 23,
    is_featured: false,
    created_at: "2025-02-01T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-07-15",
    privacy_reviewed_at: "2025-07-15",
    last_checked_at: "2025-09-30",
    approved_by: "Sarah Chen",
    internal_risk_classification: "Verification Plugin",
  },
  {
    tool_id: "tool-024",
    name: "Forensically",
    slug: "forensically",
    description: "Web-based suite of digital image forensic tools including Error Level Analysis (ELA), clone detection, and noise analysis.",
    category: "DOCUMENTS & FILE ANALYSIS",
    primary_use: "Detecting Photoshop manipulation, edited receipts, altered contract signatures, and composite images.",
    url: "https://29a.ch/sandbox/2012/imageforensics/",
    documentation_url: "https://29a.ch/sandbox/2012/imageforensics/#help",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Client-side processing in the browser: image is not sent to external server. ELA indicators require expert interpretation.",
    sort_order: 24,
    is_featured: false,
    created_at: "2025-02-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-07-20",
    privacy_reviewed_at: "2025-07-20",
    last_checked_at: "2025-10-02",
    approved_by: "Sarah Chen",
    internal_risk_classification: "Client-Side Processing",
  },

  // EVIDENCE PRESERVATION
  {
    tool_id: "tool-025",
    name: "WebPreserver",
    slug: "webpreserver",
    description: "Automated, court-admissible web and social media evidence capture system generating SHA-256 digital signatures.",
    category: "EVIDENCE PRESERVATION",
    primary_use: "Legally admissible capture of responsive social media posts, websites, video, and comments before deletion.",
    url: "https://webpreserver.com",
    documentation_url: "https://webpreserver.com/resources",
    status: "Active",
    access_type: "Subscription",
    requires_account: true,
    requires_subscription: true,
    risk_level: "Low",
    notes: "Captures full metadata, SSL certifications, and RFC 3161 timestamps. Accepted by UK Civil Courts and High Court.",
    sort_order: 25,
    is_featured: true,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-09-01",
    privacy_reviewed_at: "2025-09-01",
    last_checked_at: "2025-10-05",
    approved_by: "David Mercer",
    internal_risk_classification: "Court-Admissible Evidence Suite",
  },

  // LINK ANALYSIS
  {
    tool_id: "tool-026",
    name: "Maltego",
    slug: "maltego",
    description: "Forensic link analysis and entity graphing software for visualising complex real-world relationships.",
    category: "LINK ANALYSIS",
    primary_use: "Mapping complex multi-jurisdiction fraud schemes, corporate networks, and entity associations.",
    url: "https://www.maltego.com",
    documentation_url: "https://docs.maltego.com",
    status: "Active",
    access_type: "Freemium",
    requires_account: true,
    requires_subscription: false,
    risk_level: "Medium",
    notes: "Use Enterprise hub transforms with caution to avoid unencrypted query transmission of sensitive keywords.",
    sort_order: 26,
    is_featured: true,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-08-15",
    privacy_reviewed_at: "2025-08-15",
    last_checked_at: "2025-10-03",
    approved_by: "David Mercer",
    internal_risk_classification: "Entity Analysis Platform",
  },

  // PUBLIC OSINT DIRECTORIES & DISCOVERY
  {
    tool_id: "tool-027",
    name: "Bellingcat Online Investigation Toolkit",
    slug: "bellingcat-toolkit",
    description: "Curated collection of online tools, satellite databases, flight trackers, and investigative techniques.",
    category: "INVESTIGATOR UTILITIES",
    primary_use: "Specialised methodological guide and curated directory for advanced open-source research.",
    url: "https://www.bellingcat.com/resources/",
    documentation_url: "https://www.bellingcat.com/category/resources/how-tos/",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Peer-reviewed methods from international investigative journalists and conflict researchers.",
    sort_order: 27,
    is_featured: true,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-08-01",
    privacy_reviewed_at: "2025-08-01",
    last_checked_at: "2025-10-05",
    approved_by: "David Mercer",
    internal_risk_classification: "Curated Directory",
  },
  {
    tool_id: "tool-028",
    name: "OSINT Framework",
    slug: "osint-framework",
    description: "Structured directory of open-source intelligence resources arranged by target artifact.",
    category: "INVESTIGATOR UTILITIES",
    primary_use: "Branching discovery when researching obscure data points (e.g. IP blocks, maritime, registries).",
    url: "https://osintframework.com",
    documentation_url: "https://github.com/lockfale/osint-framework",
    status: "Active",
    access_type: "Free / Open",
    requires_account: false,
    requires_subscription: false,
    risk_level: "Low",
    notes: "Useful reference index. Some listed third-party utilities may become deprecated over time.",
    sort_order: 28,
    is_featured: false,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
    terms_reviewed_at: "2025-07-01",
    privacy_reviewed_at: "2025-07-01",
    last_checked_at: "2025-09-29",
    approved_by: "Sarah Chen",
    internal_risk_classification: "Reference Framework",
  },
];
